---
title: "Assignment 3"
author: "Michael Manigault"
date: "9/9/2020"
output: html_document
---
install.package(tidyverse)
```{r setup, include=FALSE}
```

## R Markdown

```{r}
summary(GSS$age)
sd(GSS$age, na.rm = T)
quantile(GSS$age, probs=c(0.1, 0.5, 0.9), na.rm = T)
```

```{r}
directory <- "C:/Users/Mike Jr/Desktop/"

```
```{r}
library(descr)
freq(GSS$helppoor)
GSS$helppoor <-ifelse(GSS$helppoor < 15, NA, GSS$helppoor)
freq(GSS$helppoor)

library(descr)
freq(GSS$helpblk)
GSS$helpblk <-ifelse(GSS$helpblk < 15, NA, GSS$helpblk)
freq(GSS$helpblk)


library(descr)
freq(GSS$racmar)
GSS$racmar <-ifelse(GSS$racmar < 15, NA, GSS$racmar)
freq(GSS$racmar)

library(descr)
freq(GSS$racdif1)
GSS$racdif1 <-ifelse(GSS$racdif1 < 15, NA, GSS$racdif1)
freq(GSS$racdif1)

library(descr)
freq(GSS$racdif2)
GSS$racdif2 <-ifelse(GSS$racdif2 < 15, NA, GSS$racdif2)
freq(GSS$racdif2)
```

```{r}
library(magrittr)
library(tidyverse)
library(descr)

GSS <- GSS %>%
  mutate(workblks2=8-workblks)
  table(GSS$workblks, GSS$workblks2)
```


```{r}
GSS$female<-ifelse(GSS$sex == 'female', 1, 0)
table(GSS$sex, GSS$female)

gss.2 <- GSS%>%
  select(year, racmar)%>%
mutate(racmar = ifelse (racmar == "yes", 1, 0),
  year.2 = case_when(
  year >= 1972 & year <= 1982 ~ "1972-82",
  year >= 1983 & year <= 1987 ~ "1983-87",
  year >= 1988 & year <= 1992 ~ "1988-92",
  year >= 1993 & year <= 1999 ~ "1999-93",
  year >= 2000 & year <= 2010 ~ "2000-2010"))

gss.2
glimpse(gss.2)
```




```{r}
library(sjmisc)
sjmisc::flat_table(gss.2, year.2, racmar, margin = "row")
racmar.3<-sjmisc::flat_table(gss.2, year.2, racmar, margin = "row")
```


```{r}
yearcat<-c (1970, 1980, 1990, 2000, 2010)
racmarprop<- c(.33, .24, .20, .13, .10)
racmar.2<- data.frame(yearcat, racmarprop)
racmar.2

ggplot()+
geom_line(data=racmar.2, aes(yearcat, racmarprop)) +
  labs(title = "Trends in Support for Anti-miscegeny Laws, GSS 1972-2014", x ="Years", y="Propartions")
```

